services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://symfony:symfony@db:5432/app


  nginx:
    image: nginx:alpine
    container_name: course-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:16
    container_name: course-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
